### ISSUE TITLE
python-3 compatibility

### ISSUE THREAD

**Issue by theofilos** [CodeReclaimers/btce-api#1]
/btceapi/common.py line 49 is not compatible with exceptions in python-3
I think it should change to:
    except Exception as e:
        print("Error while attempting to parse JSON response:", e)
        print ("Response:",response)
        raise e

**Comment by CodeReclaimers** [comment]
As of d61c1e0f53df408657e0a9efb9c7eff887d75dd0 this is pretty much done, although other updates done before that commit will almost certainly break your existing code.
