### ISSUE TITLE
Redundant nonce management

### ISSUE THREAD

**Issue by netaneld122** [CodeReclaimers/btce-api#17]
You could simply build a nonce method based on time, lets say:

```
    # This value is used in order to generate a small nonce, 
    # because for some reason btc-e doesn't like big nonces.
    timestamp_reduce_value = 1380736931200
    return int(time.time()*1e3) - timestamp_reduce_value
```

**Comment by CodeReclaimers** [comment]
Apologies for not getting to this (much, much) earlier...I've been entirely too busy for a long time. :)

I'm not a security person, but I suspect doing something like this with the nonce creates an opportunity for an adversary with your keys to sneak in transactions without you being alerted, as it introduces gaps into the sequence of nonces you use.  Using a contiguous sequence of nonces makes it immediately apparent that someone else is using your keys as soon as you attempt to perform an operation after they choose a nonce you haven't used yet.
