### ISSUE TITLE
Best way to get around polling failure

### ISSUE THREAD

**Issue by midnjerry** [CodeReclaimers/btce-api#36]
HI Alan,

This isn't an issue with your excellent api (or at least I haven't seen it), but what's the best way to capture exceptions and retry polling when you get 403 and SSL Errors?

Right now my bot is running on a batch file (in infinite loop) so python script can restart when any exceptions are caught.

I'm new to github and haven't figured out how to email you. :(

**Comment by CodeReclaimers** [comment]
I apologize for the long absence, I'll apply simlmx's fix in the next week or so while I'm making some other updates.

**Comment by CodeReclaimers** [comment]
@simlmx thank you for coming up with a fix for this; I've included it in commit ed16a6835791a36220136e6626746737c3060cea.
