### ISSUE TITLE
CNH

### ISSUE THREAD

**Issue by TranslucentCloud** [CodeReclaimers/btce-api#37]
Hey, Alan. Recently BTC-e has added CNH for BTC, LTC and USD. Please add these pairs.

**Comment by CodeReclaimers** [comment]
I apologize for letting this sit so long--I will be getting this code back up to date with BTC-e in the next week or so.

**Comment by CodeReclaimers** [comment]
The currencies/pairs lists have been updated to match the current BTC-e offerings.
